# ---------------------------------------------------------------------------
# Plugins (managed by TPM)
# ---------------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# ---------------------------------------------------------------------------
# General settings
# ---------------------------------------------------------------------------

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# ---------------------------------------------------------------------------
# Initialize TPM (keep this line at the very bottom of tmux.conf)
# ---------------------------------------------------------------------------
run '~/.tmux/plugins/tpm/tpm'
